### ISSUE TITLE
timestamp to refresh error on dafni login

### ISSUE THREAD

**Issue by ekfallon** [dafnifacility/cli#133]
Hi there, 
Apologies, not sure if this is an issue on my side (or I am doing something daft) - but I recently had to re-install python and all of my packages (including dafni-cli). dafni-cli installed fine but I get this error when I try the dafni login command:
(base) C:\>dafni login
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\efallon\AppData\Local\anaconda3\Scripts\dafni.exe\__main__.py", line 7, in <module>
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\dafni_cli\commands\login.py", line 16, in login
    session = DAFNISession()
              ^^^^^^^^^^^^^^
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\dafni_cli\api\session.py", line 112, in __init__
    self._obtain_session_data()
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\dafni_cli\api\session.py", line 167, in _obtain_session_data
    if not self._load_session_data():
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\dafni_cli\api\session.py", line 158, in _load_session_data
    self._session_data = dataclass_from_dict(SessionData, dictionary)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\efallon\AppData\Local\anaconda3\Lib\site-packages\dafni_cli\utils.py", line 116, in dataclass_from_dict
    return class_type(**filtered_arg_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SessionData.__init__() missing 1 required positional argument: 'timestamp_to_refresh'

**Comment by sarahbyrnie** [comment]
I believe this issue was due to having a left-over session file from using an older version of the CLI. The session file `.dafni-cli` is stored in the home directory, and deleting it will fix this problem. The session file will be deleted for you if you run the `dafni logout` command after using the CLI.
